name: CI/CD O'RDV Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: cd backend && npm install
      - name: Run unit tests
        run: cd backend && npm test

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: cd frontend && npm install --legacy-peer-deps
      - name: Run unit tests
        run: cd frontend && npm test
        env:
          CI: false
      - name: Build
        run: cd frontend && npm run build
        env:
          CI: false
